### PR TITLE
fix https://github.com/QubesOS/qubes-issues/issues/5619

### PR DESCRIPTION
**Pull request by zaoqi**
python2 is being removed and python3-YYYY is being renamed to python-YYYY.

### CODE REVIEW

**Comment by zaoqi** [comment]
@marmarek Is code in release4.0 branch python3 compatible?

**Comment by marmarek** [comment]
Now it is.

**Comment by neowutran** [comment]
@zaoqi missing signature

**Comment by marmarek** [comment]
Done in #222

**Pull request closed without merging**
