### PR TITLE
fix #6346: quit loop only when the original process is terminated

### PR DESCRIPTION
**Pull request by neowutran**
Should fix https://github.com/QubesOS/qubes-issues/issues/6346 
quit loop only when the original process is terminated.
The previous behavior was to quit the loop when any process is terminated

### CODE REVIEW

**Review by marmarek — APPROVED** [review]

**Comment by tlaurion** [comment]
@marmarek : codecov checks have not passed consequenly(?) patch is merged but no new package was deployed.
I can confirm a bug opening Nautilus under fedora-33 which closes DVM to close even if main requested app is still open. 
Seems to be same issue. Will [test](https://patch-diff.githubusercontent.com/raw/QubesOS/qubes-core-agent-linux/pull/299.patch)

**Comment by marmarek** [comment]
This fix is included in qubes-core-agent 4.0.62 (for R4.0) and 4.1.26 (for R4.1).

**Comment by marmarek** [comment]
I what went wrong - the issue reference was only in a PR description, but the one in the commit message is not formatted properly and builder-github didn't noticed it.

**Comment by tlaurion** [comment]
@marmarek I confirm this PR fixes my issue also. Not a lot of people using fedora-based DVMs nowadays it seems. Was reported by customer.

**Comment by tlaurion** [comment]
> This fix is included in qubes-core-agent 4.0.62 (for R4.0) and 4.1.26 (for R4.1).
@marmarek :
```
user@fedora ~]$ sudo dnf update qubes-core-agent --enablerepo=qubes-vm-r4.0-current-testing
Warning: Enforcing GPG signature check globally as per active RPM security policy (see 'gpgcheck' in dnf.conf(5) for how to squelch this message)
Last metadata expiration check: 0:01:45 ago on Thu Jul  8 12:37:24 2021.
Dependencies resolved.
========================================================================================================================================================================
 Package                                             Architecture              Version                           Repository                                        Size
========================================================================================================================================================================
Upgrading:
 qubes-core-agent                                    x86_64                    4.0.62-1.fc33                     qubes-vm-r4.0-current-testing                    123 k
 qubes-core-agent-dom0-updates                       x86_64                    4.0.62-1.fc33                     qubes-vm-r4.0-current-testing                     15 k
 qubes-core-agent-nautilus                           x86_64                    4.0.62-1.fc33                     qubes-vm-r4.0-current-testing                     14 k
 qubes-core-agent-network-manager                    x86_64                    4.0.62-1.fc33                     qubes-vm-r4.0-current-testing                     16 k
 qubes-core-agent-networking                         x86_64                    4.0.62-1.fc33                     qubes-vm-r4.0-current-testing                     25 k
 qubes-core-agent-systemd                            x86_64                    4.0.62-1.fc33                     qubes-vm-r4.0-current-testing                     28 k

Transaction Summary
========================================================================================================================================================================
Upgrade  6 Packages

Total download size: 221 k
Is this ok [y/N]: y^COperation aborted.
```
In current-testing where I see no report of those package updates breaking. When are they pushed into current?
Thanks

**Comment by tlaurion** [comment]
@marmarek 
```

[user@fedora ~]$ sudo rpm -qa | grep qubes-core-agent
qubes-core-agent-4.0.62-1.fc33.x86_64
qubes-core-agent-networking-4.0.62-1.fc33.x86_64
qubes-core-agent-network-manager-4.0.62-1.fc33.x86_64
qubes-core-agent-dom0-updates-4.0.62-1.fc33.x86_64
qubes-core-agent-nautilus-4.0.62-1.fc33.x86_64
qubes-core-agent-systemd-4.0.62-1.fc33.x86_64
qubes-core-agent-qrexec-4.0.62-1.fc33.x86_64
qubes-core-agent-passwordless-root-4.0.62-1.fc33.x86_64
```
Not completely fixed....

To test:

- [ ] Launching browser works.
- [ ] Launching terminal closes before Terminal is showed.

**Comment by marmarek** [comment]
>  Launching terminal closes before Terminal is showed.

Do you mean gnome-terminal? See https://www.qubes-os.org/doc/how-to-use-disposables/#starting-an-arbitrary-program-in-a-disposable-from-an-app-qube:
> The disposable will stay running so long as the process which started the disposable has not exited. Some applications, such as GNOME Terminal, do not wait for the application to close before the process exits (details here).

**Pull request merged**
