### PR TITLE
NetworkManager config - Add dns=default

### PR DESCRIPTION
**Pull request by unman**

### CODE REVIEW

**Comment by marmarta** [comment]
# OpenQA test summary
Complete test suite: https://openqa.qubes-os.org/tests/3849#dependencies
## Failed tests
* system_tests_manager
  * QubeManagerTest: [test_414_vm_state_change](https://openqa.qubes-os.org/tests/3860#step/QubeManagerTest/69)
  * QubeManagerTest: [test_500_logs](https://openqa.qubes-os.org/tests/3860#step/QubeManagerTest/71)
  * VMSettingsTest: [test_24_kernel](https://openqa.qubes-os.org/tests/3860#step/VMSettingsTest/19)
* system_tests_gui_tools
  * qubesmanager_vmsettings: [unnamed test](https://openqa.qubes-os.org/tests/3851#step/qubesmanager_vmsettings/6)
  * qubesmanager_vmsettings: [Failed](https://openqa.qubes-os.org/tests/3851#step/qubesmanager_vmsettings/7) (`# Test died: no candidate needle with tag(s) 'qubes-vm-settings work, desktop-runner-border' matched`)
  * qubesmanager_vmsettings: [unnamed test](https://openqa.qubes-os.org/tests/3851#step/qubesmanager_vmsettings/9)
* system_tests_basic_vm_qrexec_gui
  * TC_00_Basic: [test_120_start_standalone_with_cdrom_dom0](https://openqa.qubes-os.org/tests/3853#step/TC_00_Basic/4)
  * TC_00_Basic: [test_201_shutdown_event_race](https://openqa.qubes-os.org/tests/3853#step/TC_00_Basic/7)
  * TC_05_StandaloneVM_whonix-gw-15: [test_101_resize_root_img_online](https://openqa.qubes-os.org/tests/3853#step/TC_05_StandaloneVM_whonix-gw-15/3)
  * TC_05_StandaloneVM_whonix-ws-15: [test_101_resize_root_img_online](https://openqa.qubes-os.org/tests/3853#step/TC_05_StandaloneVM_whonix-ws-15/3)
  * TC_06_AppVM_debian-10: [test_121_start_standalone_with_cdrom_vm](https://openqa.qubes-os.org/tests/3853#step/TC_06_AppVM_debian-10/1)
  * TC_06_AppVM_fedora-30: [test_121_start_standalone_with_cdrom_vm](https://openqa.qubes-os.org/tests/3853#step/TC_06_AppVM_fedora-30/1)
  * TC_06_AppVM_whonix-gw-15: [test_121_start_standalone_with_cdrom_vm](https://openqa.qubes-os.org/tests/3853#step/TC_06_AppVM_whonix-gw-15/1)
  * TC_06_AppVM_whonix-ws-15: [test_121_start_standalone_with_cdrom_vm](https://openqa.qubes-os.org/tests/3853#step/TC_06_AppVM_whonix-ws-15/1)
* system_tests_backup
  * TC_10_BackupVM_whonix-ws-15: [test_100_send_to_vm_file_with_spaces](https://openqa.qubes-os.org/tests/3855#step/TC_10_BackupVM_whonix-ws-15/1)
  * TC_10_BackupVM_whonix-ws-15: [test_110_send_to_vm_command](https://openqa.qubes-os.org/tests/3855#step/TC_10_BackupVM_whonix-ws-15/2)
* system_tests_pvgrub_salt_storage
  * TC_40_PVGrub_debian-10: [test_000_standalone_vm](https://openqa.qubes-os.org/tests/3856#step/TC_40_PVGrub_debian-10/1)
  * TC_40_PVGrub_debian-10: [test_010_template_based_vm](https://openqa.qubes-os.org/tests/3856#step/TC_40_PVGrub_debian-10/2)
  * TC_40_PVGrub_fedora-30: [test_000_standalone_vm](https://openqa.qubes-os.org/tests/3856#step/TC_40_PVGrub_fedora-30/1)
  * TC_40_PVGrub_fedora-30: [test_010_template_based_vm](https://openqa.qubes-os.org/tests/3856#step/TC_40_PVGrub_fedora-30/2)
  * TC_41_HVMGrub_debian-10: [test_000_standalone_vm](https://openqa.qubes-os.org/tests/3856#step/TC_41_HVMGrub_debian-10/1)
  * TC_41_HVMGrub_debian-10: [test_010_template_based_vm](https://openqa.qubes-os.org/tests/3856#step/TC_41_HVMGrub_debian-10/2)
  * TC_41_HVMGrub_fedora-30: [test_000_standalone_vm](https://openqa.qubes-os.org/tests/3856#step/TC_41_HVMGrub_fedora-30/1)
  * TC_41_HVMGrub_fedora-30: [test_010_template_based_vm](https://openqa.qubes-os.org/tests/3856#step/TC_41_HVMGrub_fedora-30/2)

**Comment by unman** [comment]
@marmarta That's an impressive fail list, but at quick view I cant see the failures link to this PR. Am I missing something? (Answer is probably yes)

**Comment by marmarek** [comment]
No, I don't think any of those failures are related to this particular PR. I don't see any network related failures. Also, some tests fails even on the current state of R4.1.

**Comment by marmarta** [comment]
@unman , haha, yeah, this is the test iteration of an automated test result reporting script I'm working on- your PR is an accidental victim :) Reporting on whether those fails are actual regressions is incoming Soon(tm)

**Pull request merged**
