### PR TITLE
Adds qvm-copy, qvm-move, qvm-dvm support to Caja file manager.

### PR DESCRIPTION
**Pull request by makoshinra**

### CODE REVIEW

**Comment by marmarek** [comment]
Thanks for the contribution!
Few things to change:
 - you need to call make install in the new directory to have the files installed (in all three: `rpm_spec/`, `debian/` and `archlinux/`)
 - similarly, please add subpackage for Caja - similarly how it's done for Nautilus (copy&paste your friend)
 - finally, please sign your commits (see https://www.qubes-os.org/doc/code-signing/)

**Comment by makoshinra** [comment]
Thank you for the feedback @marmarek, I have updated the commits. Let me know if I've missed anything else needed for this pull request.

**Comment by marmarek** [comment]
Debian package fails to build (issue with "Depends" field - see CI logs). But otherwise it looks okay now.

**Comment by makoshinra** [comment]
Updated the commit to fix debian package build error.

**Comment by marmarek** [comment]
PipelineRetry

**Review by marmarek — APPROVED** [review]

**Pull request merged**
