### PR TITLE
Patch /etc/sudoers on Archlinux

### PR DESCRIPTION
**Pull request by alimirjamali**
fixes: https://github.com/QubesOS/qubes-issues/issues/9395

### CODE REVIEW

**Comment by alimirjamali** [comment]
The other approach would be prepending `/run/qubes/bin`  for `secure_path` in sudoers config file.

**Comment by alimirjamali** [comment]
CI/CD bot fails on building Archlinux package. The log is very cluttered and hard to analysis

**Comment by marmarek** [comment]
Maybe better place a file in `/etc/sudoers.d` instead of patching existing file?

**Comment by alimirjamali** [comment]
> Maybe better place a file in `/etc/sudoers.d` instead of patching existing file?

It is done.

**Comment by marmarek** [comment]
```
23:11:03 [qb.build_archlinux.core-agent-linux.vm-archlinux.build] make: Leaving directory '/build/qubes-vm-core/src/qubes-vm-core-4.3.5-1.1/qubes-rpc/thunar'.
23:11:03 [qb.build_archlinux.core-agent-linux.vm-archlinux.build] install: cannot create regular file '/build/qubes-vm-core/pkg/qubes-vm-core/etc/sudoers.d/qubes_secure_path': No such file or directory.
23:11:04 [qb.build_archlinux.core-agent-linux.vm-archlinux.build] .[1m.[31m==> ERROR:.[0m.[1m A failure occurred in package_qubes-vm-core()..[0m.
23:11:04 [qb.build_archlinux.core-agent-linux.vm-archlinux.build] .[1m    Aborting....[0m.
```

**Comment by alimirjamali** [comment]
I see. I already had the `/etc/sudoers.d` because of the passwordless root package. Patch is amended to create the directory.

**Pull request merged**
