### PR TITLE
Install symlinks for keys in /etc

### PR DESCRIPTION
**Pull request by DemiMarie**
This makes `qubes-dom0-update` work with metadata verification.

### CODE REVIEW

**Review by marmarek — CHANGES_REQUESTED** [review]
I think if we want Debian-based UpdateVM to verify the metadata (which will be possible with dnf there), we need to install the keys in that package too (currently they are not included under `/etc/pki/rpm-gpg`).

An alternative approach could be make `qubes-dom0-update` send the keys from dom0 (under expected paths) - which could be cleaner solution, since the keys and their paths are dictated by the repository config - which we do send from dom0.

**Comment by DemiMarie** [comment]
Pipeline retry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
> An alternative approach could be make `qubes-dom0-update` send the keys from dom0 (under expected paths) - which could be cleaner solution, since the keys and their paths are dictated by the repository config - which we do send from dom0.

Would that be under `/etc/pki/rpm-gpg`?  That seems to have a high risk of breakage.

**Comment by marmarek** [comment]
We copy rest of the dnf configuration (including yum.repos.d) into `/var/lib/qubes/dom0-updates`, so I'd assume it should go into `/var/lib/qubes/dom0-updates/etc/pki/rpm-gpg`, but I'm not sure whether will it work (specifically, if key paths are affected by the `--installroot` option or not).

**Comment by DemiMarie** [comment]
> We copy rest of the dnf configuration (including yum.repos.d) into `/var/lib/qubes/dom0-updates`, so I'd assume it should go into `/var/lib/qubes/dom0-updates/etc/pki/rpm-gpg`, but I'm not sure whether will it work (specifically, if key paths are affected by the `--installroot` option or not).

I highly doubt it.  In particular, there would otherwise be no way to install into an empty chroot.

**Comment by marmarek** [comment]
Indeed, you are right (just tested it). But we could patch the key path(s) using `qubes-download-dom0-updates.sh` script, though. Depending on a specific VM configuration files for downloading dom0 updates is a layering violation. This is also why we use dnf.conf sent by dom0 and repositories config from dom0 (even though dom0 doesn't really make use for real repository configs).

**Comment by DemiMarie** [comment]
https://github.com/QubesOS/qubes-core-admin-linux/pull/68/commits/79fa7e43b239769d7039eda38d8bf6176a1b1f66 modifies `qubes-dom0-update` to upload the keys and patch the repository files.

**Comment by DemiMarie** [comment]
Closing in favor of https://github.com/QubesOS/qubes-core-admin-linux/pull/68, which handles this more generically.

**Pull request closed without merging**
