### PR TITLE
qfile-agent: use a dirfd instead of getcwd()

### PR DESCRIPTION
**Pull request by rustybird**
Fixes QubesOS/qubes-issues#8516

### CODE REVIEW

**Comment by marmarek** [comment]
Thanks for working on this!
Can you try to also add/extend test for this case? We have very similar already at https://github.com/QubesOS/qubes-core-admin/blob/main/qubes/tests/integ/vm_qrexec_gui.py#L605

**Comment by rustybird** [comment]
Since [it turned out](https://github.com/QubesOS/qubes-issues/issues/8516#issuecomment-1722305933) that Demi had already fixed the data loss on a more general level (with that fix including a test) and it just wasn't backported to R4.1 yet:

I've added some test code here in this repo to test the tools in `qubes-rpc/` independently. The Filecopy test cases pipe `qfile-agent` into `qfile-unpacker` locally. `test_10_shadowed_by_mount` covers an example of the most essential failure mode related to the new bug, which is `qfile-agent` sending the wrong file *successfully*.

**Comment by rustybird** [comment]
PipelineRetry

**Comment by rustybird** [comment]
PipelineRetryFailed

**Comment by rustybird** [comment]
Hmm in checks:tests it can't find the qubes-utils-libs and qubes-utils-devel packages for installation, and my tests are skipped.

Can/should I configure Qubes OS package repos somehow?

**Comment by marmarek** [comment]
> Hmm in checks:tests it can't find the qubes-utils-libs and qubes-utils-devel packages for installation, and my tests are skipped.
> 
> Can/should I configure Qubes OS package repos somehow?

In other similar cases, we build dependencies in CI via a local git clone:
- https://github.com/QubesOS/qubes-core-qrexec/blob/main/.gitlab-ci.yml#L20-L22
- https://github.com/QubesOS/qubes-core-admin/blob/master/.gitlab-ci.yml#L14

This approach allows testing against `main` branch, even if no package is built, but also eases switching CI container to another distro (like bumping its version before proper packages are uploaded for given Fedora version).
If that would work here without too much complications, I'd prefer this approach. But if yuu run into some dependency issues (like needing to clone/build 3+ more repositories), then probably it isn't worth it, and its easier to add qubes repository then (accepting the downsides). Fortunately, core-agent-linux is the place where we have qubes repository definitions, so you don't need to copy them from elsewhere.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
