### PR TITLE
qvm-copy(-to-vm.gnome): avoid 'find -files0-from' for bullseye

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by rustybird** [comment]
@marmarek should `repro:bookworm` maybe be marked `allowed to fail`?

**Comment by marmarek** [comment]
> Should `repro:vm-bookworm` maybe be marked `allowed to fail`?

It's an issue only in this repo (https://github.com/QubesOS/qubes-issues/issues/8315) and I'm not sure how to do that with our configuration all included from one place...

**Comment by rustybird** [comment]
Oh, I didn't realize that spamming `PipelineRetryFailed` will eventually work for `repro:vm-bookworm` even in this repo. I'll do that.

**Review by marmarek — APPROVED** [review]

**Comment by rustybird** [comment]
@marmarek this still needs to be cherry-picked for R4.1

**Pull request merged**
